### ISSUE TITLE
Unable to assign issue

### ISSUE THREAD

**Issue by lacarnesecca** [StackStorm-Exchange/jira#48]
I am getting the error `'accountId' must be the only user identifying query parameter in GDPR strict mode.`, which per Jira's docs was resulting of an [API change in 2019](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/).  To fix this issue the package should be updated and tested ([to the current pip version](https://pypi.org/project/jira/)).

**Comment by arm4b** [comment]
Thanks for the report!
PRs contributions are welcome to fix this!
