### ISSUE TITLE
Jira issue priority not included in output of jira.get_issue

### ISSUE THREAD

**Issue by stfn775** [StackStorm-Exchange/jira#63]
The action "jira.get_issue" is not returning the issue's priority, even if it is available over API and is set.
It seems to be missing from `lib/formatters.py`

    result = {
        'id': issue.id,
        'key': issue.key,
        'url': url,
        'summary': issue.fields.summary,
        'description': issue.fields.description,
        'status': issue.fields.status.name,
        'resolution': resolution,
        'labels': issue.fields.labels if hasattr(issue.fields, 'labels') else [],
        'reporter': reporter,
        'assignee': assignee,
        'created_at': issue.fields.created,
        'updated_at': issue.fields.updated,
        'resolved_at': issue.fields.resolutiondate
    }

https://github.com/StackStorm-Exchange/stackstorm-jira/blob/3802b522a59ad27a89eecb6cb2be40ae9477016f/actions/lib/formatters.py#L30C1-L44C6

**Comment by arm4b** [comment]
Thanks for the report. A PR to improve this would be welcome!

**Comment by stfn775** [comment]
PR done. Thanks! :)
