### ISSUE TITLE
JIRA SUBTASK action in JIRA pack

### ISSUE THREAD

**Issue by zsmanjot** [StackStorm-Exchange/jira#71]
Currently we have the JIRA actions to create a JIRA ticket, to update JIRA fields , to link one issue with the other issue but could not see any action where in we can have the option to create a subtask under the same ticket.

Could we have it in the pack please?

**Comment by floatingstatic** [comment]
@zsmanjot would you be able to submit a pull request for this?

**Comment by jpavlav** [comment]
👋 Hello @zsmanjot! Thankfully you can use the `create_issue` action to create a subtask under another ticket. Running it via the `st2` client would look something like this:

```bash
st2 run jira.create_issue summary="Test Subtask" type="<name_of_subtask_issue_type>" extra_fields='{"parent": {"key": "<key_of_parent_jira_ticket"}}'
```

You'll need to know what `type` corresponds with `subtasks` in your JIRA org. Once you have that, you should be set. If you need to find out what issue types exist, you can use the `jira` api [createmeta](https://developer.atlassian.com/server/jira/platform/jira-rest-api-example-discovering-meta-data-for-creating-issues-6291669/) endpoint to discover which ones will work.

**Comment by jpavlav** [comment]
Also @zsmanjot if this is insufficient, it is possible to create an action that makes this more straight-forward, perhaps by using the `jira` python library to call `createmeta()`, accept a `type` as a parameter and a `key` for a parent. It could iterate over the available types and ensure the one specified is a `subtask` and fail if not.

Either way, if my suggestion above is sufficient, please respond. If not, I think I'd be up for creating an action to do this specific thing.

**Comment by floatingstatic** [comment]
Thanks for the excellent suggestions @jpavlav . Apologies for not digging a little deeper on this one. @zsmanjot if the suggestions above work for you can we close this issue? Thanks!

**Comment by zsmanjot** [comment]
Hi @jpavlav 

Thanks for the help and yes i tried it but, it does ask for some extra inputs that needs to be provided. I will try it out again.

@floatingstatic Yes sure , this issue can be closed. I will update with my findings later.
