### ISSUE TITLE
Add Dashboard Support

### ISSUE THREAD

**Issue by jpavlav** [StackStorm-Exchange/jira#72]
👋 Hey friends!

I have something I'm working on over at DigitalOcean. We use StackStorm for a lot of our automation. The project I'm working on currently is to create a dynamically updated dashboard as a sort of prioritization system for folks doing operational work on our infra. I've submitted a PR to `pycontribs/jira` to that end.

https://github.com/pycontribs/jira/pull/1837

I've been chatting with some of the maintainers over there and someone should be getting around to reviewing it soon. Anyway, I'm going to be working on a branch on my fork of this repo to implement these dashboard-related actions. I'll submit a PR once I'm finished, but realize, it probably shouldn't make it into `main` until the `jira` lib has also merged my changes into `main` over there.

Anyway, just wanted to give a heads up! Thanks for building this pack! And I'm looking forward to contributing 😄.

**Comment by floatingstatic** [comment]
Thanks, I added a similar comment in #73  just now prior to seeing this. Once we have changes upstreamed into `jira` I think this is fine to add and have no problems merging given these are new actions not affecting any existing actions in the pack. Thanks for the contribution.

**Comment by jpavlav** [comment]
Just made a comment on the PR to the same effect but, https://github.com/pycontribs/jira/pull/1837 has been merged and was included in https://github.com/pycontribs/jira/releases/tag/3.7.0 (which has since been bumped once more to `3.8.0` and published to `pypi`).

**Comment by floatingstatic** [comment]
Closed in #73
